import Head from "next/head";
import Footer from "../../components/Footer";
import HeaderNav from "../../components/Header/Header";
import PageContainer from "../../components/HOC/PageContainer";
import SectionContainer from "../../components/HOC/SectionInner";

export default function Faq() {
  return (
    <div>
      <Head>
        <title>FineTurtle | Home</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderNav />

      <PageContainer>
        <SectionContainer name="faq">
          <div className="max-w-[500px]">
            <h1 className="title-page text-6xl lg:text-7xl uppercase mb-32">
              We are pionneers of digital real estate
            </h1>
          </div>
          <div className="grid lg:grid-cols-3 gap-14">
            <FaqBlock title="Is there any chance holders will ever be able to earn real money from FineTurtle?">
              <p className="mb-6">
                The Fine ecosystem will be a universe of limitless possibility
                that enables holders to earn passive income. Therefore, once we
                build FineTurtle NFTs into a strong Web 3.0 brand, our holders
                will be able to earn hard cash!
              </p>
              <p className="mb-6">
                The more the Fine brand grows, more value will be created in our
                real estate tokenization project. This will bring on board
                investors and partners with whom we will expand operations.
              </p>
              <p className="mb-6">
                Once earnings from selling real estate tokens start trickling
                in, our NFT holders will then get a chance to earn interest on
                their staked NFTs. For those who will have bought the real
                estate tokens using FINET, they will earn dividends directly
                from the revenue generated by the real estate projects.
              </p>
              <p>
                The value of our NFTs will also grow exponentially and community
                members will be able to sell them at a great profit too!
              </p>
            </FaqBlock>
            <FaqBlock title="What are the benefits of staking FineTurtle NFTs?">
              <p className="mb-6">
                Staking NFTs simply means locking them up in a smart contract
                for a predetermined time period in order to earn rewards. In
                this case, you as a member of our community will earn Fine
                Tokens (FINET) when you stake your FineTurtle NFTs.
              </p>
              <p className="mb-2">
                With the Fine Tokens you earn, you will be able to;
              </p>
              <ul className="list-disc">
                <li>
                  Purchase collectibles from the FineTurtle Mutation collection
                </li>
                <li>
                  Participate in great auctions of various NFTs and digital
                  assets
                </li>
                <li>
                  Stand a chance to own real estate in real life once you have
                  enough real estate tokens
                </li>
                <li>
                  Attend Fine dinners specifically meant for members of the Fine
                  Turtle community
                </li>
              </ul>
            </FaqBlock>
            <FaqBlock title="Any real-life benefits?">
              <p className="mb-6">
                Of course! Not to be self-absorbed but frankly speaking, Fine
                Turtle is probably the NFT project with the most practical
                benefits for holders in real life.
              </p>
              <p className="mb-2">
                This is because FineTurtle holders will enjoy;
              </p>
              <ul className="list-disc">
                <li>
                  Spectacular and exclusive merchandise and various high quality
                  fashion items
                </li>
                <li>
                  Dining in fine, high-end restaurants with the best hospitality
                  services
                </li>
                <li>
                  Access to workout sessions in high-end gyms that are fully
                  equipped and run by fitness pros
                </li>
                <li>VIP access to several first-class hotels and resorts</li>
                <li>
                  Discounted prices and exclusive offers on Fine merchandise
                  unlike in any other NFT project
                </li>
              </ul>
            </FaqBlock>
            <FaqBlock title="What makes FineTurtle NFTs Different?">
              <p className="mb-6">
                Pioneering the seamless merge of the world of NFTs with that of
                real estate through tokenization of assets to provide liquidity
                solutions
              </p>
              <ul className="list-disc">
                <li>
                  NFTs built using unique, original traits as opposed to auto-
                  generated trait templates
                </li>
                <li>The most creative and imaginative NFT artwork</li>
                <li>
                  A secure ecosystem for acquiring and selling high-end NFTs
                  without having to worry about cyberattacks and theft
                </li>
                <li>
                  The most vibrant and cohesive NFT community that shares a
                  strong passion for the Metaverse and all it has to offer
                </li>
                <li>
                  Innovative combination of quality artwork and maximum utility
                  for our NFT community
                </li>
                <li>
                  An NFT community where every member has a voice in how the
                  affairs are run
                </li>
              </ul>
            </FaqBlock>
            <FaqBlock title="Giving back the only way we can">
              <p className="mb-6">
                There is no doubt members of the Fine Turtle community will
                enjoy wonderful perks and benefits for their participation.
                However, do you know what’s more? The Fine Turtles NFT project
                will also set a stage for people to grow in their personal
                capacities too!
              </p>
              <p className="mb-6">
                How? Well, FineTurtle will have a one-of-its-kind innovation hub
                called Fine Lab. Here, we will welcome talented artists with
                diverse inspirations to put their creativity to use. That way,
                we will offer them a platform to grow and showcase their skills.
              </p>
              <p>
                Consequently, these artists will find a footing in the NFT space
                and go on to break newer boundaries. We will also collaborate
                with well-known artists to give them exposure to our platform
                while also deriving value from their work to benefit FineTurtle
                NFT holders.
              </p>
            </FaqBlock>
          </div>
        </SectionContainer>
      </PageContainer>

      <Footer />
    </div>
  );
}

const FaqBlock = (props) => {
  const { title, children } = props;

  return (
    <div className="">
      <div className="bg-[color:var(--theme-primary)] w-[10px] h-[10px] mb-6" />
      <div className="text-2xl font-polysans-bulky mb-6">{title}</div>
      <div className="">{children}</div>
    </div>
  );
};
